title: Ruslan Kim
email: i.kim.ruslan.89@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site of Ruslan Kim
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruslankim.com" # the base hostname & protocol for your site, e.g. http://example.com
youtube_username: necdtsa
twitter_username: ikimruslan
github_username:  kirussell
linkedin_username: kirussell
instagram_username: metakimruslan

# Build settings
theme: minima
plugins:
  - jekyll-feed